### ISSUE TITLE
{1.19.4} Internal Server Error when sitting in boat or mounting horse

### ISSUE THREAD

**Issue by tavschke** [Alpvax/GoProne#18]
did some debugging and found that there is an issue when mounting or sitting on objects 

here is the log on the console

        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: alpvax.mc.goprone.GoProne@6a47b7a7 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.NoSuchFieldError: f_122903_
        at TRANSFORMER/goprone@1.19-2.0.4/alpvax.mc.goprone.validation.RidingCheck.<clinit>(RidingCheck.java:15)
        at TRANSFORMER/goprone@1.19-2.0.4/alpvax.mc.goprone.PlayerProneData.setRiding(PlayerProneData.java:45)
        at TRANSFORMER/goprone@1.19-2.0.4/alpvax.mc.goprone.PlayerProneData.playerTick(PlayerProneData.java:64)
        at TRANSFORMER/forge@45.0.49/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150)
        at TRANSFORMER/goprone@1.19-2.0.4/alpvax.mc.goprone.GoProne.onPlayerTick(GoProne.java:88)
        at TRANSFORMER/goprone@1.19-2.0.4/alpvax.mc.goprone.__GoProne_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@45.0.49/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:835)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.world.entity.player.Player.m_8119_(Player.java:213)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:261)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.network.Connection.m_129483_(Connection.java:255)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:910)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273)        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252)
        at java.base/java.lang.Thread.run(Thread.java:833)

[13:01:45] [Server thread/WARN] [minecraft/ServerConnectionListener]: Failed to handle packet for /192.168.1.1:55673
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:261) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.Connection.m_129483_(Connection.java:255) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:910) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.lang.NoSuchFieldError: f_122903_
        at alpvax.mc.goprone.validation.RidingCheck.<clinit>(RidingCheck.java:15) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at alpvax.mc.goprone.PlayerProneData.setRiding(PlayerProneData.java:45) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at alpvax.mc.goprone.PlayerProneData.playerTick(PlayerProneData.java:64) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19.4-45.0.49-universal.jar%23106!/:?] {re:classloading}
        at alpvax.mc.goprone.GoProne.onPlayerTick(GoProne.java:88) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at alpvax.mc.goprone.__GoProne_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:835) ~[forge-1.19.4-45.0.49-universal.jar%23106!/:?] {re:classloading}
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:213) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        ... 9 more
[13:01:45] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Tavschkee lost connection: Internal server error
[13:01:45] [Server thread/INFO] [minecraft/MinecraftServer]: Tavschkee left the game
[13:02:01] [User Authenticator #2/INFO] [minecraft/ServerLoginPacketListenerImpl]: UUID of player Tavschkee is 4b0c29f5-a329-411c-89d3-73515622f448
[13:02:02] [Server thread/INFO] [minecraft/PlayerList]: Tavschkee[/192.168.1.1:55796] logged in with entity id 1255 at (1208.6875, 62.07326432466506, 947.5669568442985)
[13:02:02] [Server thread/INFO] [minecraft/MinecraftServer]: Tavschkee joined the game
[13:02:02] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Could not initialize class alpvax.mc.goprone.validation.RidingCheck
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: alpvax.mc.goprone.GoProne@6a47b7a7 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.NoClassDefFoundError: Could not initialize class alpvax.mc.goprone.validation.RidingCheck
        at TRANSFORMER/goprone@1.19-2.0.4/alpvax.mc.goprone.PlayerProneData.setRiding(PlayerProneData.java:45)
        at TRANSFORMER/goprone@1.19-2.0.4/alpvax.mc.goprone.PlayerProneData.playerTick(PlayerProneData.java:64)
        at TRANSFORMER/forge@45.0.49/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150)
        at TRANSFORMER/goprone@1.19-2.0.4/alpvax.mc.goprone.GoProne.onPlayerTick(GoProne.java:88)
        at TRANSFORMER/goprone@1.19-2.0.4/alpvax.mc.goprone.__GoProne_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@45.0.49/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:835)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.world.entity.player.Player.m_8119_(Player.java:213)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:261)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.network.Connection.m_129483_(Connection.java:255)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:910)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273)        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664)
        at TRANSFORMER/minecraft@1.19.4/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: f_122903_ [in thread "Server thread"]
        at TRANSFORMER/goprone@1.19-2.0.4/alpvax.mc.goprone.validation.RidingCheck.<clinit>(RidingCheck.java:15)
        ... 20 more

[13:02:03] [Server thread/WARN] [minecraft/ServerConnectionListener]: Failed to handle packet for /192.168.1.1:55796
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:261) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.Connection.m_129483_(Connection.java:255) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:910) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.lang.NoClassDefFoundError: Could not initialize class alpvax.mc.goprone.validation.RidingCheck
        at alpvax.mc.goprone.PlayerProneData.setRiding(PlayerProneData.java:45) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at alpvax.mc.goprone.PlayerProneData.playerTick(PlayerProneData.java:64) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19.4-45.0.49-universal.jar%23106!/:?] {re:classloading}
        at alpvax.mc.goprone.GoProne.onPlayerTick(GoProne.java:88) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at alpvax.mc.goprone.__GoProne_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:835) ~[forge-1.19.4-45.0.49-universal.jar%23106!/:?] {re:classloading}
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:213) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        ... 9 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: f_122903_ [in thread "Server thread"]
        at alpvax.mc.goprone.validation.RidingCheck.<clinit>(RidingCheck.java:15) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at alpvax.mc.goprone.PlayerProneData.setRiding(PlayerProneData.java:45) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at alpvax.mc.goprone.PlayerProneData.playerTick(PlayerProneData.java:64) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19.4-45.0.49-universal.jar%23106!/:?] {re:classloading}
        at alpvax.mc.goprone.GoProne.onPlayerTick(GoProne.java:88) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading}
        at alpvax.mc.goprone.__GoProne_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[goprone-1.19-2.0.4.jar%2399!/:1.19-2.0.4] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:835) ~[forge-1.19.4-45.0.49-universal.jar%23106!/:?] {re:classloading}
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:213) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.19.4-20230314.122934-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        ... 9 more

**Comment by tavschke** [comment]
UPDATE: found out that hopping in boat on singleplayer is fine but multiplayer it causes this error so the error is multiplayer based

**Comment by Alpvax** [comment]
Update to the latest version of the mod. version 2.0.4 doesn't actually support 1.19.4

**Comment by Alpvax** [comment]
Already fixed
